### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a basic `html` skeleton with car `img`
- [x] Style background to look like grass
- [x] Filter out unnecessary styling
- [x] Test in incognito browser
- [x] Fix errors
