### ISSUE TITLE
User Can Turn Their Car

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/driving-game#4]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  Create 4 `transform: rotate` classes
- [x] Set their value to `0deg`, `90deg`, `180deg`, and `270deg`
- [x] Create a `data.js` file with an `obj` named data
- [x] Make sure data has one property: `currentDirection` set to the value of the 'right'
- [ ] Query the `img` and give it a `transform: rotate` class based on which directional key was pressed
- [ ] Make sure `data.currentDirection` reflects any changes in direction
- [ ] Delete unnecessary styling
- [ ] Check output in incognito browser
- [ ] fix errors
